[package]
name = "ci"
version = "0.1.0"
edition = "2021"
license = "MIT"
description = "CI script for isomaze"
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
xshell = "0.2"
bevy = "0.12"